### ISSUE TITLE
GEOMETRY_GIT_NO_COMMIT_MESSAGE not working out of the box.

### ISSUE THREAD

**Issue by MarioRicalde** [jedahan/geometry#1]
The "no commits" functionality on the git function doesn't seem to be working as intended out of the box.

After reading the code I found about that variable that once set it suddenly works, although it has some issues with formatting, `no::commits` instead of `no commits`.

![image](https://user-images.githubusercontent.com/125900/52731325-13bebf80-2f83-11e9-87e3-23d333eaf349.png)

```
macOS Mojave 10.14.3
iTerm2 3.2.7
zsh 5.7.1 (x86_64-apple-darwin18.2.0)
```

**Comment by MarioRicalde** [comment]
Fixed on e036337a5dbecb3f0c17e70645250807f6264e63

**Comment by jedahan** [comment]
(unfortunately, had to use 'no-commits' instead of 'no commits' since we use ` ` as a separator)

**Comment by MarioRicalde** [comment]
That's actually the solution I was going to propose, it's the easiest. Good call. Thanks for the fix.
