### ISSUE TITLE
geometry_exec_time not cleaning up after enter prompt.

### ISSUE THREAD

**Issue by MarioRicalde** [jedahan/geometry#10]
![image](https://user-images.githubusercontent.com/125900/52899849-777bff00-31b4-11e9-9eeb-59687100496a.png)

The expected result would be to just show it once for the previous command, and pressing <enter> without a command shouldn't display it.

**Comment by jedahan** [comment]
okay so there are two ways I can fix this. One is to not display rprompt when using geometry_info, like so:
<img width="828" alt="screen shot 2019-02-17 at 6 22 23 pm" src="https://user-images.githubusercontent.com/32407/52921051-02f2ae80-32e1-11e9-9efb-1d6c5d71979a.png">

The other is to re-run the full prompt, which is a tiny bit laggy

<img width="823" alt="screen shot 2019-02-17 at 6 23 29 pm" src="https://user-images.githubusercontent.com/32407/52921072-26b5f480-32e1-11e9-89d3-193670ea28d2.png">

Which would be best?

**Comment by jedahan** [comment]
I pushed the second change to the branch since it is a partial fix, but I wonder if the first feels better or not.

**Comment by MarioRicalde** [comment]
I can't really notice any issues with performance or anything that makes it too laggy. But that might be my hardware? Unsure.

**Comment by jedahan** [comment]
So I will mark this as closed and open a new issue for feedback as a possible UX enhancement.
