### ISSUE TITLE
Bug with dynamic GEOMETRY_RPROMPT

### ISSUE THREAD

**Issue by jedahan** [jedahan/geometry#11]
seems like I cannot reset GEOMETRY_RPROMPT just by setting it to a new array.

**Comment by MarioRicalde** [comment]
How can this be reproduced? What's the expected result?

**Comment by jedahan** [comment]
If i do `GEOMETRY_RPROMPT=()` the right prompt does not disappear, for example

**Comment by MarioRicalde** [comment]
Good job!
