### ISSUE TITLE
async.zsh inside the repo?

### ISSUE THREAD

**Issue by MarioRicalde** [jedahan/geometry#13]
@jedahan what's the reasoning behind keeping the `zsh-async` library on demand like that? Is there anything preventing us from including it in the repo in some other fashion?

**Comment by jedahan** [comment]
if someone already is manually managing it? Maybe we can do both - keep in repo but only load if needed...

**Comment by MarioRicalde** [comment]
I would keep it in the repo and just load it. If a user wants to specify
another one give them a variable and if it’s set include theirs.
