### ISSUE TITLE
%s causes unexpected output 

### ISSUE THREAD

**Issue by MarioRicalde** [jedahan/geometry#14]
![image](https://user-images.githubusercontent.com/125900/54490110-a69b9400-4878-11e9-962d-ee3ff73fac06.png)

Left is wit hgeometry on, right without.

**Comment by MarioRicalde** [comment]
I'm wondering what could be causing this, quite an interesting one if it's indeed geometry. I'm guessing it is because it only happens when I enable geometry.

**Comment by jedahan** [comment]
It has to do with `geometry::set_title`, and figuring out how to escape that correctly

**Comment by jedahan** [comment]
Should be fixed in https://github.com/jedahan/geometry/commit/3f9077ff53638acfd439bc819080635ce40c6fda , on the simple-async branch

**Comment by MarioRicalde** [comment]
This indeed is fixed in that branch. Any reason why you're keeping it separate? Do you intend to merge it? 

Cheers.

**Comment by jedahan** [comment]
I will merge the fix into mnml for now, it was just the branch I was working from :-p
