### ISSUE TITLE
pty command already used: geometry

### ISSUE THREAD

**Issue by MarioRicalde** [jedahan/geometry#15]
![image](https://user-images.githubusercontent.com/125900/54497782-534f3300-48c4-11e9-8aa9-1d284878d409.png)

Oddly enough I've been seeing the message above at random points. I have not been able to successfully reproduce it 100% but it's something to keep an eye on.

**Comment by jedahan** [comment]
@MarioRicalde can you try the `simple-async` branch? If you get no errors, I will merge simple-async into `mnml` and then cut a release next week.

**Comment by MarioRicalde** [comment]
@jedahan I'm going to be testing that branch for the time being. I'll let you know if I find any issues.

**Comment by MarioRicalde** [comment]
So far nothing seems to be coming up from that branch. Closing this for the time being.
