### ISSUE TITLE
How to add a HH:MM clock?

### ISSUE THREAD

**Issue by psprint** [jedahan/geometry#19]
I would like to add a clock string "[HH:MM] " on the left edge of the main prompt. How to accomplish this?

**Comment by jedahan** [comment]
So the tricky part with that is if you want it to re-render every minute. Here is one way to do it.

```zsh
# ~/.zshrc
mnml_clock() { date -u +"[%H:%M]" }   # render the time
TMOUT=15; TRAPALRM() { mnml::prompt } # rerender the prompt every 15 seconds
MNML_PROMPT=(mnml_clock $MNML_PROMPT) # place time first in prompt
```

**Comment by jedahan** [comment]
I added that to the [functions wiki page](https://github.com/jedahan/mnml/wiki/functions)

**Comment by psprint** [comment]
Thanks, it works well. I like the clock to be a snapshot of time of when the prompt appeared, so I didn't use the trap.
