### ISSUE TITLE
Not compatible with zplug

### ISSUE THREAD

**Issue by MarioRicalde** [jedahan/geometry#3]
When attempting to use your branch with `zplug` I get the following warning.

```shell
WARNING:  Failed to load "~/.zplug/repos/jedahan/geometry/geometry.zsh-theme" (jedahan/geometry)
```

The code in `.zshrc` is:

```shell
zplug "jedahan/geometry", at:mnml, as:theme
```

Possibly related:
[zplug/zplug#424 (comment)](https://github.com/zplug/zplug/issues/424#issuecomment-320523980)

The prompt seems to work, you just get that warning.

```
macOS Mojave 10.14.3
iTerm2 3.2.7
zsh 5.7.1 (x86_64-apple-darwin18.2.0)
zplug 2.4.2
```

**Comment by jedahan** [comment]
So when I try `zsh -x geometry.zsh` it fails with `+/Users/micro/.zr/geometry/geometry.zsh:64> echo 'Error: Could not load zsh-async library.'
Error: Could not load zsh-async library.`
which is why zplug warns.

**Comment by MarioRicalde** [comment]
You're absolutely right!

**Comment by jedahan** [comment]
I spent a bit of time trying to fix this but did not make progress, open to others taking a stab and refactoring how we load async

**Comment by MarioRicalde** [comment]
If you remove the `||` statement, it seems to load just fine, from what I can tell.

**Comment by MarioRicalde** [comment]
Either that or I'm misinterpreting the output from `zsh -x`

**Comment by jedahan** [comment]
yeah but that means `source async.zsh` is failing, which seems bad

**Comment by MarioRicalde** [comment]
@jedahan the thing is, the file is loaded and sourced properly because I can access variables declared from within the `async.zsh`, you can even echo the `ASYNC_VERSION` ( or whatever var that was ).

How can we test the functionality itself of `async.zsh`?

**Comment by jedahan** [comment]
Yeah good point. I think I'll loosen the checks, and just look for `((ASYNC_INIT_DONE))`. Latest version is pushed, can you test it with zplug and see if its fixed now?

**Comment by MarioRicalde** [comment]
Will do as soon as I’m back at my computer. Saw the changes, makes sense.

**Comment by MarioRicalde** [comment]
Apologies on the delay on getting back to you about this issue.

Apparently, the issue is persisting as of the current branch.

```WARNING:  Failed to load "~/.zplug/repos/jedahan/geometry/geometry.zsh-theme" (jedahan/geometry)```

**Comment by MarioRicalde** [comment]
```
△ ~ source ~/.zplug/repos/jedahan/geometry/geometry.zsh-theme
△ ~ echo $?
1
```

The exact same case as what they mention [here](https://github.com/zplug/zplug/issues/424#issuecomment-320523980).

**Comment by MarioRicalde** [comment]
```zsh -x geometry.zsh-theme```

Has the following output:

```
+/Users/m/.zplug/repos/jedahan/geometry/geometry.zsh-theme:87> geometry::rprompt
+geometry::rprompt:1> RPROMPT=''
+geometry::rprompt:2> zle
+geometry::rprompt:3> async_stop_worker geometry
+async_stop_worker:1> setopt localoptions noshwordsplit
+async_stop_worker:3> local ret=0 worker k v
+async_stop_worker:4> worker=geometry
+async_stop_worker:12> async_unregister_callback geometry
+async_unregister_callback:1> typeset -gA ASYNC_CALLBACKS
+async_unregister_callback:3> unset 'ASYNC_CALLBACKS[geometry]'
+async_stop_worker:13> zpty -d geometry
+async_stop_worker:13> ret=1
+async_stop_worker:16> typeset -gA ASYNC_PROCESS_BUFFER
+async_stop_worker:17> unset 'ASYNC_PROCESS_BUFFER[geometry]'
+async_stop_worker:20> return 1
```

**Comment by MarioRicalde** [comment]
So...

``` 
geometry::rprompt() {
  RPROMPT="${(j/::/)3}"
  zle && zle reset-prompt
  async_stop_worker geometry
  echo $@
}
```

By doing that, it suddenly loads well and you can see some warnings related to the right side tools.

```
▲ ~ geometry::wrap 0     0.0202190876 geometry_exec_time:zstat:1: /var/folders/dk/gtpnkjx56zn53ffk30ydlt5h0000gn/T//geometry_exec_time: no such file or directory
geometry_exec_time:2: bad math expression: operand expected at end of string
geometry::wrap:4: command not found: geometry_hg 0
```

Apparently you can do `return 0` and it works instead of the `echo $@`. How do we know the library is working as expected?

**Comment by jedahan** [comment]
Awesome debugging! I added `GEOMETRY_DEBUG` to the latest push and have turned that on to see other plugins that are leaking non-zero statuses, and slowly have been reducing them.

**Comment by jedahan** [comment]
Okay, I made a bunch of changes regarding `rprompt` that should fix things

**Comment by MarioRicalde** [comment]
Amazing, I'll check it tomorrow when I wake up.

Cheers mate and thanks for the "thank you" on the `README.md`.

**Comment by MarioRicalde** [comment]
Apologies for the delay on testing this. Been slightly busy.

I stashed all my changes and synced up with your branch, and I'm getting this injected into the prompt. Is this the intended behavior?

![image](https://user-images.githubusercontent.com/125900/52894046-0c590b00-3169-11e9-9b24-8ed64211a65d.png)

I also notice in there a potential issue with `hg`, looking into it and opening the relevant ticket.

**Comment by MarioRicalde** [comment]
Alright, this is working properly. Good job.
