### ISSUE TITLE
Question: Current looks VS previous version. 

### ISSUE THREAD

**Issue by MarioRicalde** [jedahan/geometry#4]
I notice that we have some differences between what's on the main branch and this one, so I was wondering if matching that is part of your goal for this branch, or we're trying to stay relatively different from the current production one? 

Please advice, since I see some differences and I'm unsure if I should report them. @jedahan

**Comment by jedahan** [comment]
There are lots of minor differences, some that just reflect my personal style for things. If there is something significant the original branch does that the new one cannot do, then I'd consider it a bug that we likely want to support.

The difference in default layout is a relatively large change, but I think its useful in differentiating that this is a 2.0.

If enough people liked geometry because of the (path symbol) on left and (git exec_time) on right, then I'd be open to making those the defaults again.

**Comment by MarioRicalde** [comment]
Without modifying any direct file from geometry, can a user match the looks from the old one with on this branch?

I reckon that's a good way to test the configuration options. Thoughts?

**Comment by jedahan** [comment]
I believe this would give the same defaults as the original:
```
GEOMETRY_PROMPT=(geometry_path geometry_status)
GEOMETRY_RPROMPT=(geometry_exec_time geometry_git geometry_hg)  
```

**Comment by MarioRicalde** [comment]
I'm going to look into trying them side by side, and then see if I can make it a 1 to 1. I'll update this issue once I have it.

**Comment by MarioRicalde** [comment]
![image](https://user-images.githubusercontent.com/125900/52899922-71d2e900-31b5-11e9-9f56-81ed15be8ac1.png)
![image](https://user-images.githubusercontent.com/125900/52899948-beb6bf80-31b5-11e9-8d3b-bc525734d83d.png)


First one is how it looks in `geometry-zsh/geometry` currently. The second one is the prompt and rprompt variables you added above. Third one is this branch as is.

Any thoughts on the differences?

**Comment by jedahan** [comment]
WIth these updated settings below, I see some differences.

No ' :: ' between branch name and other git info (my preference is the new way of rendering, not having the GIT_SEPARATOR between the branch and other info).

No space before the left prompt (I think this is a good change in theory, but looks less nice in your screenshot).

Extra space in the right prompt (Looks bad, should be fixed)

```
GEOMETRY_PROMPT=(geometry_status geometry_path)
GEOMETRY_RPROMPT=(geometry_exec_time geometry_git geometry_hg)
GEOMETRY_GIT_SEPARATOR=" :: "
```

**Comment by jedahan** [comment]
going to migrate this issue upstream to decide if its a blocker or not

**Comment by jedahan** [comment]
I've fixed the left & right prompt spacing by adding a `geometry_echo` command, and adding that to the defaults of GEOMETRY_{R}PROMPT in the appropriate places. The rest of the differences are marked in the PR upstream https://github.com/geometry-zsh/geometry/pull/238#discussion_r258964923
