### ISSUE TITLE
How and Where to write documentation?

### ISSUE THREAD

**Issue by MarioRicalde** [jedahan/geometry#6]
Wiki? README?

I think we have to add some more documentation about what's available for customizing, like for instance:

`GEOMETRY_EXEC_TIME_PATIENCE`

**Comment by jedahan** [comment]
I'd say start with the wiki if we are going to document every option.
I would like the readme to stay small and focused. Maybe we can make an options.md to contain documentation on everything...

**Comment by MarioRicalde** [comment]
I like the idea of keeping `README.md` as lean as possible.

So how about we go with creating more files as it makes sense for documentation.

I imagine we need:

1. options documentation
2. upgrading steps and notes.

cc: @justmendes
