### ISSUE TITLE
geometry_virtualenv is hard to read.

### ISSUE THREAD

**Issue by MarioRicalde** [jedahan/geometry#8]
While reading through the `functions` one of them popped out like a sore thumb, and it was the `geometry_virtualenv`.

Thoughts?

**Comment by jedahan** [comment]
How does this look https://github.com/jedahan/geometry/commit/2ddf1f599407e0a07dd7dce5efeb41321d1a34d6 ?

**Comment by MarioRicalde** [comment]
Beautiful. Good job my friend.
